# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise32"
  config.vm.synced_folder "../master", "/srv/salt"
  config.vm.provision :salt do |salt|
    salt.minion_config = "minion.conf"
    salt.run_highstate = true
    salt.install_type = "stable"
  end

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8180, host_ip: "127.0.0.1"

  # Yandex Tank need 512MB memory
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end
end