# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "phalcon125-apache2-php54-mysql55"
  config.vm.box_url = "https://s3-eu-west-1.amazonaws.com/phalcon/phalcon125-apache2-php54-mysql55.box"
  config.vm.network "private_network", ip: "192.168.56.20"

end
